apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
  namespace: recommendations
spec:
  selector:
    app: recommendations-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer