apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecasting-api
  namespace: forecasting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forecasting-api
  template:
    metadata:
      labels:
        app: forecasting-api
    spec:
      containers:
      - name: forecasting-api
        image: 388691194728.dkr.ecr.us-east-1.amazonaws.com/forecasting-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENDPOINT_NAME
          value: "xgboost-water-1773502392"
        - name: AWS_REGION
          value: "us-east-2"
        - name: TEAM_NAME
          value: "forecasting"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10