apiVersion: v1
kind: ResourceQuota
metadata:
  name: forecasting-quota
  namespace: fraud
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi